### ISSUE TITLE
Widgets for Gratipay 2.0

### ISSUE THREAD

**Issue by mattbk** [gratipay/grtp.co#103]
I realized this should be here rather than at https://github.com/gratipay/gratipay.com/issues/3603.

Pretty sure widgets are still linked to users, not teams, and probably don't reflect the right amount received anyway after Gratipocalypse.
##### Plan
- [ ] ossify `data-{gittip,gratipay}-widget=button` (no longer dynamic; always just "Gratipay")
- [ ] implement a new widget or button for Teams
- [ ] publish a page under https://gratipay.com/about/  about upgrading widgets
- [ ] show "Please upgrade" when `data-{gittip,gratipay}-widget=default` and `data-{gittip,gratipay}-username`
##### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2534
##### When [milestone](https://github.com/gratipay/grtp.co/milestones/Make%20Widgets%202.0) accomplished
- [ ] https://github.com/gratipay/gratipay.com/issues/3924

**Comment by mattbk** [comment]
+1 from https://github.com/RunestoneInteractive/RunestoneComponents/commit/a8d1713512a028befef5743266b815672c0f41d3

**Comment by e9t** [comment]
+1
I've changed the handle from my user account to team account, but seeing "I receive $0.00 / wk on Gratipay." on my widget instead of the proper amount of donations.

Many wishes on resolving Gratipocalypse!

**Comment by whit537** [comment]
Thanks @e9t! We're gettin' there! :-)

The API issue on the gratipay.com side is https://github.com/gratipay/gratipay.com/issues/3726.

**Comment by mattbk** [comment]
So if we fix the API, will the widgets work automatically?

**Comment by techtonik** [comment]
@mattbk I don't see a clear explanation what API is broken, so before fixing it, somebody needs to research, what was that API expected response, where was the endpoint and then I can investigate what is broken.

**Comment by mattbk** [comment]
I'll try to take a look this weekend.

**Comment by mattbk** [comment]
This seems to have been fixed in https://github.com/gratipay/gratipay.com/issues/3726.

**Comment by mattbk** [comment]
Teams: The receiving value is a link that should go to the team page, however it goes to http://gratipay.com/undefined.

~Users: The receiving link is correct, although in my case it says "anonymously" for the value, which used to be hooked to a setting that I can't find now.

**Comment by mattbk** [comment]
Moved from gratipay/gratipay.com#3726.

Hot dog, the API and Widget works for teams!

I get the following Team widget though (https://gratipay.com/northern-plains-athletics/public.json), need to fill in trailing zeros:
![image](https://cloud.githubusercontent.com/assets/3729038/11963547/607e0656-a8ad-11e5-8c77-3ba35e7477a1.png)

**Comment by mattbk** [comment]
For teams, the widget should say "This team receives" rather than "I receive."

**Comment by techtonik** [comment]
Or "XXX team receives"

**Comment by rummik** [comment]
It used to say 'We receive', rather than 'I receive', if it was a team receiving, but the APIs changed and the widget didn't get updated along with.

**Comment by techtonik** [comment]
"We receive" is better that 3rd party reference.

**Comment by whit537** [comment]
I think what we want to do is make the existing widgets that are already out in the wild as backwards compatible as possible. They are there to represent what are now ~users.

 1. Widgets already in the wild should be updated to reflect giving and taking for ~users.
 1. We should implement new widgets for teams, rather than trying to conflate them.

**Comment by mattbk** [comment]
Widgets in the wild were built to include Teams 1.0, as far as I can tell.

It sounds right to split them now that Teams 2.0 aren't as close to ~users as Teams 1.0 were to ~users 1.0, I just need to find the time to figure it out.

**Comment by whit537** [comment]
😞 

> $undefined #Gratipay @ http://promisejs.org  :)

![cgzgrokw8aeu3ox](https://cloud.githubusercontent.com/assets/134455/14655913/aaa19ee8-0652-11e6-82bd-f6edd2b4d184.jpg)

https://twitter.com/GeorgeChetreanu/status/722342060137832449

**Comment by mattbk** [comment]
> I think what we want to do is make the existing widgets that are already out in the wild as backwards compatible as possible. They are there to represent what are now ~users.

> 1. Widgets already in the wild should be updated to reflect giving and taking for ~users.
> 2. We should implement new widgets specifically for Teams.

So first we need a PR that takes the existing ~user widgets and reterms "receiving" as" taking."

Secondly, we need to build a _separate_ widget for teams to use.

I think I can use pieces of https://github.com/gratipay/grtp.co/issues/112 for the latter.

**Comment by mattbk** [comment]
> So first we need a PR that takes the existing ~user widgets and reterms "receiving" as" taking."

https://github.com/gratipay/grtp.co/pull/133

**Comment by mattbk** [comment]
> We should implement new widgets specifically for Teams.

There are at least three ways to do this:

- clone `lib/` and modify the API from the bottom up
- have a switch in `v1.js` that points to a different `api.js` just for teams
- have a switch at the top of `api.js` that points to variations of the functions for teams
- clean up https://github.com/gratipay/grtp.co/issues/112 so it is just about adding team functionality; depends on merging #133.

No idea which is right, from a programming standpoint.

**Comment by whit537** [comment]
Alright, thinking this through with @kaguillera ...

What are the widgets we have out in the wild right now?

### First Generation

**Entrypoint**: https://gratipay.com/whit537/widget.html

Depends on redirects from `www.gittip.com` to `gratipay.com`.

```
<iframe style="border: 0; margin: 0 0 -3pt 3pt; padding: 0;"
        src="https://www.gittip.com/whit537/widget.html"
        width="48pt" height="22pt"></iframe>
```

This used to be dynamic but now it's static, it just [displays `Gratipay`](https://github.com/gratipay/gratipay.com/blob/1951/www/~/%25username/widget.html.spt#L107) all the time.

### Second Generation

**Entrypoint**: https://grtp.co/v1.js

Users embed [a `<script>` tag](https://github.com/gratipay/gratipay.com/blob/1951/www/~/%25username/widgets/index.html.spt#L101-L163) that loads `//grtp.co/v1.js`. Depends on redirects from `gttp.co` to `grtp.co`.

```
<script data-gratipay-username="whit537"
        data-gratipay-widget="button"
        src="//grtp.co/v1.js"></script>
```

```
<script data-gratipay-username="whit537"
        src="//grtp.co/v1.js"></script>
```

```
<script data-gratipay-username="whit537"
        data-gratipay-widget="giving"
        src="//grtp.co/v1.js"></script>
```

**Comment by whit537** [comment]
Fundamentally those are the two widgets we have out there right now. The first generation ain't goin' no where. We leave that alone. Congrats on being early.

What are we doing with https://grtp.co/v1.js?

**Comment by whit537** [comment]
Well lookie here:

http://grtp.co/v1/widgets/
http://grtp.co/v1/widgets/button.html
http://grtp.co/v1/widgets/default.html
http://grtp.co/v1/widgets/giving.html

**Comment by whit537** [comment]
Huh. Promise.js (https://github.com/gratipay/grtp.co/issues/103#issuecomment-212134269) inlined us:

![screen shot 2016-04-27 at 5 12 39 pm](https://cloud.githubusercontent.com/assets/134455/14868377/4a34f4ca-0c9b-11e6-9b12-7c93a952ba4f.png)

https://www.promisejs.org/static/3.0.19/gittip-widget/client.js

**Comment by whit537** [comment]
Alright, so consider this: all of the Gratipay 1.0 *receiving* widgets that are out there—they represent ~users that could/should apply for a new Team account. Sure, we could probably hackishly mostly transparently upgrade their widget to show *taking* instead ... but! Another option would be to make the widgets say something like "Upgrade Gratipay!" with a link to a page under gratipay.com/about explaining the situation and how to get back on track.

![screen shot 2016-04-27 at 5 31 54 pm](https://cloud.githubusercontent.com/assets/134455/14868858/f6a28b08-0c9d-11e6-9b45-db3923d98413.png)

The *giving* widgets should be fine. The second-generation buttons we can drop back to just `Gratipay` as we did for the first generation ones.

**Comment by whit537** [comment]
But in that case we should have new Team widgets ready to embed before we prompt people to upgrade.

**Comment by whit537** [comment]
Waddya think, @mattbk?

**Comment by whit537** [comment]
> Another option would be to make the widgets say something like

We would do that for any widget that had `data-{gittip,gratipay}-username` and the default `data-{gittip,gratipay}-widget`.

**Comment by mattbk** [comment]
That makes sense.

**Comment by mattbk** [comment]
So we should build a `v2` widget that is cloned and then modified from the `v1` widget. This new version will handle giving in the same way, but will handle taking (for ~users) and receiving (for teams).

**Comment by whit537** [comment]
@mattbk Just a heads-up: I'm going to focus on https://github.com/gratipay/gratipay.com/issues/3994 through May. I'll be happy to work on this further with you after that! :)

**Comment by mattbk** [comment]
Not a problem.

**Comment by mattbk** [comment]
https://github.com/gratipay/grtp.co/issues/103#issuecomment-215227273

Keep in mind that first generation has no version, and second generation entrypoint is `v1.js`.

Third generation should be `v2.js` then.

**Comment by mattbk** [comment]
I just closed my open PRs to lessen the confusion. Don't have one started for third-generation widgets yet, but there are pieces in https://github.com/gratipay/grtp.co/issues/133 and https://github.com/gratipay/grtp.co/issues/112.

**Comment by mattbk** [comment]
In https://github.com/gratipay/grtp.co/pull/138, I stub out a basic working `v2` for Teams only. The idea is that (for now) Teams can use `v2` and ~users can continue using `v1`.

**Comment by whit537** [comment]
> The idea is that (for now) Teams can use `v2` and ~users can continue using `v1`.

And once v2 is deployed we'll modify v1 to show "Please upgrade," ya?

**Comment by mattbk** [comment]
Ya.

**Comment by whit537** [comment]
##### Key

**bold** = default
_italic_ = deprecated ("Please upgrade")

## Current Widgets

| 1.0 users | 2.0 ~users | 2.0 Teams |
|--------|-----------|-----------|
| **receiving** | — | — |
| button | — | — |
| giving | — | — |

## Current + 1: #138

| 1.0 users | 2.0 ~users | 2.0 Teams |
|--------|-----------|-----------|
| **receiving** | — | **receiving** |
| button | — | — |
| giving | — | — |

## ...

## Current + N

| 1.0 users | 2.0 ~users | 2.0 Teams |
|--------|-----------|-----------|
| _receiving_ | — | — |
| _button_ | — | — |
| _giving_ | — | — |

**Comment by whit537** [comment]
@mattbk I'm struggling over here, because I think we need to somewhat shift the direction we're going with this ticket. I think if we zoom out, the _real_ pain point we're trying to address here is that currently we have no option for Teams to embed any sort of Gratipay-branded thing on their own website after they've signed up. Yes?

The question @kaguillera and I are wrestling with over here is whether the design of the old Gittipay 1.0 widgets is good enough to try to bring back, as we're attempting to do in #138. Ultimately I think we want to move more in the direction of a direct call-to-action button a la [PayPal](https://www.paypal.com/webapps/mpp/get-started/donate-button), [Stripe](https://stripe.com/docs/checkout), [Coinbase](https://developers.coinbase.com/docs/merchants/payment-buttons), [Patreon](https://wordpress.org/plugins/patron-button-and-widgets-by-codebard/screenshots/), or [Gumroad](https://gumroad.com/widgets). We've been attempting this over in https://github.com/gratipay/gratipay.com/issues/1167 for a while now (and we also have a simple button of a certain style in another [repo](https://github.com/gratipay/gratipay-badge)). I've closed that ticket in favor of this one.

I guess I want us to deliver something that we can be proud of, and I'm not sure this is it:

![screen shot 2016-06-25 at 11 45 37 am](https://cloud.githubusercontent.com/assets/3729038/16357975/9584b358-3acb-11e6-821c-ece9d855dca1.png)

I think we want to line ourselves up alongside fine buttons such as these:

![screen shot 2016-06-29 at 4 07 09 pm](https://cloud.githubusercontent.com/assets/134455/16467063/9cfee34c-3e13-11e6-96a0-efdaf0653028.png)

![screen shot 2016-06-29 at 4 08 53 pm](https://cloud.githubusercontent.com/assets/134455/16467141/fc9d3b8c-3e13-11e6-86a2-fedaa20e6f2c.png)

And of course, the venerable:

![screen shot 2016-06-29 at 4 09 24 pm](https://cloud.githubusercontent.com/assets/134455/16467110/e1cc02c0-3e13-11e6-981a-88fd532438ba.png)

The strength of the button is in the brand. Stripe takes a more white-label approach, though of course their modal is instantly recognizable; on [Django](https://www.djangoproject.com/fundraising/):

![screen shot 2016-06-29 at 4 14 18 pm](https://cloud.githubusercontent.com/assets/134455/16467262/8ff6d168-3e14-11e6-9ce9-5f57a6c3c23c.png)

![screen shot 2016-06-29 at 4 16 36 pm](https://cloud.githubusercontent.com/assets/134455/16467338/e7388b7e-3e14-11e6-9687-3e31ed977efb.png)

Of these examples, Gumroad is the strongest parallel for us, I think. Since we have a social layer in addition to the processing infrastructure layer, it makes sense for us to have _some_ branding (not completely white label). I like Gumroad's light touch compared to Patreon (and gratipay-badge). PayPal is just old-school, of course. Gumroad's focus is on their customer—the "my" in "Buy *my* product" is not Gumroad. They also have [the best widget builder of the bunch](https://gumroad.com/widgets). Drool. 💧

**Comment by whit537** [comment]
So I guess my question is, how do we get there from here? Obviously we need to take incremental steps—a _lot_ of work that went into Gumroad's experience.

![mvp](https://cloud.githubusercontent.com/assets/134455/16468119/5f0d40f6-3e18-11e6-96d4-c0585585a9c3.png)

([h/t](http://blog.crisp.se/2016/01/25/henrikkniberg/making-sense-of-mvp))

**Comment by whit537** [comment]
Honestly, this drives me back to https://github.com/gratipay/gratipay.com/issues/3665 and https://github.com/gratipay/inside.gratipay.com/issues/298.

**Comment by whit537** [comment]
Here's a Gumroad screenshot ftr:

![screen shot 2016-06-29 at 8 16 13 pm](https://cloud.githubusercontent.com/assets/134455/16472894/5de1dcbe-3e36-11e6-8b9e-7a6be2a8c42e.png)

**Comment by icarito** [comment]
Breaking the widget was a bad idea and not having an alternative (even static) is a shame! The old widget offers a <red>Error</red>, quite ugly!

**Comment by icarito** [comment]
Gratitude, by the way, for being open and all ;-)

**Comment by whit537** [comment]
Sorry for the trouble, @icarito. 😞

Check this out for the latest widget we have to offer:

https://github.com/gratipay/grtp.co#examples

For a static alternative see here:

https://github.com/gratipay/gratipay-badge#gratipay-badge

**Comment by whit537** [comment]
> I guess the main issue is there's no documentation from the home page that I could find!

Agreed, we need to bring back documentation on Gratipay.com itself.

**Comment by mattbk** [comment]
> Agreed, we need to bring back documentation on Gratipay.com itself.

https://github.com/gratipay/gratipay.com/issues/3924

**Comment by mattbk** [comment]
Example of OpenCollective checkout: 
![image](https://cloud.githubusercontent.com/assets/3729038/21432624/0113abb2-c832-11e6-9f60-916261e51b4b.png)

**Comment by clone1018** [comment]
That's Stripe right?
