### ISSUE TITLE
Switch to Gulp?

### ISSUE THREAD

**Issue by rummik** [gratipay/grtp.co#77]
I've been playing with Gulp for a while now, and really love its use of streams and support for incremental builds.  Seems like it would be a great idea to switch over to reduce build times, and testing time.

**Comment by techtonik** [comment]
See also http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

**Comment by rummik** [comment]
@techtonik Two points that post doesn't cover:

- Incremental builds - Right now we have `grunt watch`, and would have an equivalent Gulp task for watching for changes, so when a file is written it'll automatically build it locally, saving you a lot of time.  
- Watchers - With incremental builds, only the files affected by the change are rebuilt, which a `npm jshint` or `npm uglify` wouldn't handle.  Yes, we could roll our own watchers, but I don't personally see it as being worth the time investment.

**Comment by clone1018** [comment]
+1 gulp

**Comment by techtonik** [comment]
Looks like watch is possible - http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/#watch but I do not insist.

**Comment by galuszkak** [comment]
+1 for gulp.

@techtonik in my experience gulp is much more handy, than plain tasks defined in package.json . One thing to point out is (IMO) that it is also much more readable.

**Comment by techtonik** [comment]
Grunt gave me some headache when I was tuning Vagrant, and browser jstests still fail to run. Will going Gulp fix that? https://github.com/gratipay/gratipay.com/issues/3000

**Comment by techtonik** [comment]
Info how to do testing with Gulp - http://twin.github.io/selenium-testing-workflow-with-webdriverio/

**Comment by techtonik** [comment]
Working on that yesterday/today.

**Comment by rummik** [comment]
@techtonik There's a lot of work towards this in the v2 branch

**Comment by techtonik** [comment]
@rummik https://github.com/gratipay/grtp.co/pull/81 looks like a big step to complete (and test are failing). Can we just factor out Gulp part into Widgets 1.5 PR? In that case I will be able to review and merge it without QR part. I prefer to tasks in single `gulpfile.js` for direct comparison with Grunt.

In my PR - https://github.com/gratipay/grtp.co/pull/108 - I also started to introduce ESLint instead of JSHint, so I am afraid that more things we spend on scripts, the more features creep in. Perhaps you can give me a review and/or add commits to that `gulp` branch to make it complete?

**Comment by rummik** [comment]
@techtonik I probably won't have time to do that until the weekend at the soonest, but I'll see what I can do

**Comment by techtonik** [comment]
@rummik would be awesome!

**Comment by whit537** [comment]
This seems to have stalled out.
